spring:
  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      settings:
        web-allow-others: false # disable remote access
  jpa:
    show-sql: true
